// Generated by Qodo Gen

const { median } = require('..');

describe('median', () => {


    // Calculate median for an odd-length array
    it('should return the middle element when the array length is odd', () => {
      const inputs = [1, 3, 2];
      const result = median(inputs);
      expect(result).toBe(2);
    });

    // Handle empty array input
    it('should return NaN when the input array is empty', () => {
      const inputs = [];
      const result = median(inputs);
      expect(result).toBeNaN();
    });
});
