const { variance } = require('..');

// Generated by Qodo Gen

describe('variance', () => {

    // Calculate variance for a list of positive numbers
    it('should return the correct population variance when given a list of positive numbers', () => {
      const inputs = [1, 2, 3, 4, 5];
      const result = variance(inputs);
      expect(result).toBeCloseTo(2);
    });
    it('should return the correct sample variance when given a list of positive numbers', () => {
        const inputs = [1, 2, 3, 4, 5];
        const result = variance(inputs, false);
        expect(result).toBeCloseTo(2.5);
      });

    // Calculate variance for an empty list
    it('should return NaN when given an empty list', () => {
      const inputs = [];
      const result = variance(inputs);
      expect(result).toBeNaN();
    });
});
