"use strict";
exports.__esModule = true;
exports.variance = exports.standardDeviation = exports.coefficientOfVariation = exports.averageDeviation = void 0;
var standardDeviation = require("./standard-deviation");
exports.standardDeviation = standardDeviation;
var variance = require("./variance");
exports.variance = variance;
var averageDeviation = require("./average-deviation");
exports.averageDeviation = averageDeviation;
var coefficientOfVariation = require("./coefficient-variation");
exports.coefficientOfVariation = coefficientOfVariation;
